services:
  postgres:
    container_name: postgres-db
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=mydatabase"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=myuser"
    ports:
      - "5432:5432"

  pgadmin4:
    container_name: pgadmin4-web
    image: "dpage/pgadmin4:latest"
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@example.com
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050
