CREATE TABLE IF NOT EXISTS jobs (
  id VARCHAR(50) NOT NULL,
  jobTitle VARCHAR(255) NOT NULL,
  company VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  appliedDate VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
);